"""Safe ransomware-behaviour simulator (for testing and demos only).

Exercises GreyRun's detection and response without any real malware. Safety
guarantees:

* It operates only inside a dedicated sandbox directory that it creates and
  stamps with a marker file. It re-verifies the marker before touching anything
  and refuses to act on a directory it did not make.
* It generates its own throw-away sample documents and rewrites only those.
* It does not spread, makes no network calls, and cannot reach files outside
  the sandbox.

It reproduces the observable behaviour of an encryption sweep (overwriting
files with random bytes, appending a locked extension, dropping a ransom note)
so the detector has something to detect.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass
from typing import List, Optional

from . import console, utils

MARKER = ".greyrun_sandbox"
SAMPLE_EXTS = [".txt", ".docx", ".xlsx", ".csv", ".doc", ".md", ".rtf"]


def _sample_body(i: int) -> bytes:
    lines = [
        f"Project notes and quarterly summary -- document #{i}",
        "This is throwaway sample content generated by GreyRun's drill mode.",
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.",
        "Account,Region,Quarter,Revenue,Notes",
    ]
    for r in range(60):
        lines.append(f"{1000+r},Region_{r%5},Q{(r%4)+1},{(r*913)%100000}.00,ok")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


@dataclass
class SandboxInfo:
    path: str
    files: List[str]


def make_sandbox(base_dir: Optional[str] = None, num_files: int = 40) -> SandboxInfo:
    """Create a sandbox directory full of harmless sample documents."""
    if base_dir:
        root = utils.normpath(base_dir)
    else:
        import tempfile

        root = utils.normpath(os.path.join(tempfile.gettempdir(), "greyrun_sandbox"))
    utils.ensure_dir(root)

    # Stamp it so the attack phase can verify it is really our sandbox.
    marker_path = os.path.join(root, MARKER)
    with open(marker_path, "w", encoding="utf-8") as fh:
        fh.write("GreyRun sandbox -- safe to delete.\n")

    files: List[str] = []
    for i in range(num_files):
        ext = SAMPLE_EXTS[i % len(SAMPLE_EXTS)]
        name = f"sample_{i:03d}{ext}"
        path = os.path.join(root, name)
        try:
            with open(path, "wb") as fh:
                fh.write(_sample_body(i))
            files.append(path)
        except OSError:
            continue
    return SandboxInfo(path=root, files=files)


def _assert_sandbox(path: str) -> None:
    """Refuse to operate on anything that is not a marked GreyRun sandbox."""
    root = utils.normpath(path)
    if not os.path.isdir(root):
        raise RuntimeError(f"Sandbox path is not a directory: {root}")
    if not os.path.exists(os.path.join(root, MARKER)):
        raise RuntimeError(
            f"Refusing to run simulation: {root} is not a GreyRun sandbox "
            f"(missing {MARKER} marker). The simulator only touches sandboxes "
            f"it created with `greyrun simulate --setup`."
        )


@dataclass
class AttackResult:
    encrypted: int
    note_path: Optional[str]
    extension: str


def simulate_attack(
    sandbox_dir: str,
    extension: str = ".locked",
    note_name: str = "HOW_TO_DECRYPT.txt",
    delay: float = 0.05,
    drop_note: bool = True,
) -> AttackResult:
    """Mimic an encryption sweep *inside the sandbox only*."""
    _assert_sandbox(sandbox_dir)
    root = utils.normpath(sandbox_dir)

    console.warn("DRILL: simulating ransomware behaviour inside sandbox only")
    console.info(f"Sandbox: {root}")

    targets = [
        p
        for p in utils.iter_files([root])
        if os.path.basename(p) != MARKER
        and not p.endswith(extension)
        and os.path.basename(p) != note_name
    ]

    encrypted = 0
    real_root = os.path.realpath(root)
    for path in targets:
        # Re-verify every iteration; defence in depth. Resolve symlinks
        # (realpath) so a reparse point can't redirect a write outside the box.
        try:
            real_path = os.path.realpath(path)
        except OSError:
            continue
        if not utils.is_within(real_path, [real_root]) or not os.path.exists(
            os.path.join(root, MARKER)
        ):
            break
        try:
            # Real ransomware clears read-only/hidden/system attributes before
            # encrypting so it can overwrite protected files; mirror that here
            # (otherwise truncating-open fails on hidden canaries on Windows).
            if os.name == "nt":
                try:
                    import ctypes

                    ctypes.windll.kernel32.SetFileAttributesW(str(path), 0x80)
                except Exception:
                    pass
            size = max(2048, os.path.getsize(path))
            with open(path, "wb") as fh:
                fh.write(os.urandom(size))  # high-entropy => "encrypted"
            os.replace(path, path + extension)  # append locked extension
            encrypted += 1
        except OSError:
            continue
        if delay:
            time.sleep(delay)

    note_path = None
    if drop_note:
        note_path = os.path.join(root, note_name)
        try:
            with open(note_path, "w", encoding="utf-8") as fh:
                fh.write(
                    "YOUR FILES HAVE BEEN ENCRYPTED (SIMULATION)\r\n\r\n"
                    "This is a harmless GreyRun drill. No real files were affected.\r\n"
                    "Delete this folder to clean up.\r\n"
                )
        except OSError:
            note_path = None

    console.ok(f"DRILL complete: {encrypted} sandbox files 'encrypted' with {extension}")
    return AttackResult(encrypted=encrypted, note_path=note_path, extension=extension)


def cleanup(sandbox_dir: str) -> int:
    """Delete a sandbox directory (only if it carries the marker)."""
    _assert_sandbox(sandbox_dir)
    import shutil

    root = utils.normpath(sandbox_dir)
    try:
        # Clear any read-only bits a lockdown may have set, then remove.
        for f in utils.iter_files([root]):
            try:
                if os.name == "nt":
                    import ctypes

                    ctypes.windll.kernel32.SetFileAttributesW(str(f), 0x80)
                else:
                    os.chmod(f, 0o644)
            except Exception:
                pass
        shutil.rmtree(root)
        return 1
    except OSError:
        return 0
